name: Upload pydevd-pycharm wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ther version of pyedevd-pycharm to publish'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
      - uses: actions/checkout@v3
      - run: curl -L https://github.com/JetBrains/intellij-community/archive/refs/tags/pycharm/${{ inputs.version }}.tar.gz > pycharm.tar.gz
      - run: python3 prepare.py ${{ inputs.version }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -L https://github.com/JetBrains/intellij-community/archive/refs/tags/pycharm/${{ inputs.version }}.tar.gz > pycharm.tar.gz
      - run: python3 prepare.py ${{ inputs.version }}

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

